spring:
#  data:
#    mongodb:
#      host: auth-mongodb
#      username: user
#      # password: ${MONGODB_PASSWORD}
#      password: admin
#      database: piggymetrics
#      port: 27017
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:13306/spcloud?useSSL=false
    username: root
    password: admin


server:
  servlet:
    context-path: /uaa
  port: 5000

