spring:
  data:
    mongodb:
      host: auth-mongodb
      username: user
      # password: ${MONGODB_PASSWORD}
      password: admin
      database: piggymetrics
      port: 27017

server:
  servlet:
    context-path: /uaa
  port: 5000

logging:
  level: debug
